### ISSUE TITLE
Scrolling through big docblocks

### ISSUE THREAD

**Issue by manulaiko** [php-integrator/atom-tooltips-legacy-php56#23]
It happens that when the docblock from the tooltip is too big, a scrollbar appears on the right, however it's impossible to use since when you move the mouse the tooltip disappears.

Screenshot:

![https://i.snag.gy/R5tWkp.jpg](https://i.snag.gy/R5tWkp.jpg "https://i.snag.gy/R5tWkp.jpg")

Also, I've been trying to make the core parse markdown on docblocks but I couldn't find where they're parsed, because it replaces certain characters making it not-that-worth parsing it in the tooltip package (you can see in code blocks that spaces at the beginning of the line are deleted and *"* are replaced with *&quote;*). Where are the docblocks parsed in the core?

**Comment by Gert-dev** [comment]
Yes, that is a problem and one I have been wondering about for a while now. I see a couple of solutions, but neither offer the same convenience as the current tooltips:

* We switch to a tooltip that doesn't disappear when the mouse exits the item or one that only triggers on a keyboard shortcut. This will allow you to move the mouse over the tooltip to scroll. You would need to close it with a close button, a keyboard shortcut, or by clicking outside it.
* We require control/alt/cmd/... to be held while hovering and as long as you hold down the modifier key, the popup stays active. However, this may pose problems or require hacks as you'll be doing a `control/alt/cmd/... + scroll` instead of a normal scroll.
* We switch to some sort of documentation pane at the bottom (i.e. using something like the `bottom-dock` package, which is also used by `linter-manager` and `gulp-manager`). This still requires some kind of trigger for the documentation to become active or visible. We could dismiss the pane by pressing e.g. escape.

Regarding markdown support for docblocks (taken up in [this core ticket](https://github.com/php-integrator/core/issues/7)): docblock parsing can be found in the [src/Parsing/DocblockParser.php](https://github.com/php-integrator/core/blob/master/src/Parsing/DocblockParser.php) file. A heads up: this is a homegrown class that has been around since the start and is far from complete. This is also the class that does the "magic" escaping in `sanitizeText`. I investigated [switching to ReflectionDocBlock](https://github.com/php-integrator/core/issues/6) instead a while ago, but that has other issues unfortunately.

I believe there was also some contradiction to what format of text docblocks may contain and PSR-5 doesn't clarify yet whether they "MUST" or "MAY" be markdown. Supporting plain text, HTML _and_ markdown seems a bit absurd and I would, at least for the moment, solely support markdown (unless it is somehow easier to support all of these at once) as markdown mostly inherently displays plain text correctly anyway.

Also, a final note: when indexing files, docblocks are parsed, but built-in structural elements from PHP itself are parsed using a PHP documentation parser (which [may change in the future](https://github.com/php-integrator/core/issues/2)). These don't use the docblock parser, but I thought I'd mention this since these may contain a different format from normal docblocks, which may be relevant if you're looking into updating the CoffeeScript side. This parsing can be found in [src/Indexing/BuiltinIndexer.php](https://github.com/php-integrator/core/blob/master/src/Indexing/BuiltinIndexer.php#L474) in `getNormalizedDocumentation`.

**Comment by manulaiko** [comment]
I'm don't know too much about atom plugin development, but if you could check mouse position it would be possible to see if the mouse is inside the tooltip and if it's not, delete it.
But for now, I think the easiest (and probably smoother) solution would be to autoscroll the tooltip if it's too big.

Also, about the markdown, an option could be letting the user choose how it's going to be parsed.

Thanks for the reply!

**Comment by Gert-dev** [comment]
Your suggestion to delete it when the mouse leaves the tooltip sounds good in theory, but in practice there will likely be a tiny gap between the bounding box of the element the mouse hovers on and the tooltip itself, resulting in the mouseout event firing before the mouse moves over the tooltip itself. However, I can probably fix that with some kind of timeout before the tooltip hides again, so it may be worth investigating anyway, thanks for the tip!

If markdown for docblock descriptions makes it into the core, I'll likely just solely support that. The idea of giving the user the choice sounds nice, but as the PSR-5 standard explicitly mentions markdown, some projects are already using it, and it won't affect most plain text docblocks, it seems a bit superfluous to carry the maintenance burden of supporting all of them.

**Comment by Gert-dev** [comment]
Hello! I'm moving all relevant tickets from this repository to the base package as this functionality is now part of the base package.

I see that this one has basically been implemented in base package 3.0: tooltips are now displayed in a scrollable dock.
